### ISSUE TITLE
Error when bumping cloudflare-tunnel from 0.1.1 to 0.1.2

### ISSUE THREAD

**Issue by ashwin153** [rlex/helm-charts#1]
When I bumped the version of cloudflare-tunnel from `0.1.1` to `0.1.2` I get the following error.

```
Error: YAML parse error on cloudflare-tunnel/templates/deployment.yaml: error converting YAML to JSON: yaml: line 19: did not find expected key
```

The only change that was made between `0.1.1` and `0.1.2` was the addition of the following line.

https://github.com/rlex/helm-charts/blob/bee4cd282d3eb8b040fa718bdf4ba282bf628ffb/charts/cloudflare-tunnel/templates/deployment.yaml#L18

Shouldn't it be `.Template.BasePath` and not `$.Template.BasePath`?

**Comment by rlex** [comment]
That's interesting. The only thing that line does is adding annotation with shasum of configmap so tunnel can be restarted in case of config change, and it work for me. Mind sharing helm version you're using? And i should probably add chart testing workflow to repo...

**Comment by rlex** [comment]
configmap checksum trick was taken directly from helm docs: https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments

I'm not familiar with terraform-helm, so just to rule out possibility of conflict with terraform, can you try deploying same chart with same values skipping terraform?

**Comment by ashwin153** [comment]
Here's my `values.yaml` file.

```yaml
cloudflared:
  ingress:
    - service: http_status:404
  tunnel: ad5fce10-aa7e-4e91-9c17-06ae7b13a03e
  tunnelSecret: cloudflared-credentials
fullnameOverride: cloudflared
nodeSelector:
  "cloud.google.com/gke-nodepool": cloudflared
```

Here's what happens when I install it with Helm.

```bash
$ helm install cloudflared-test rlex/cloudflare-tunnel --version 0.1.2 --values values.yaml 
Error: YAML parse error on cloudflare-tunnel/templates/deployment.yaml: error converting YAML to JSON: yaml: line 19: did not find expected key
```

Here's my Helm version.

```bash
$ helm version
version.BuildInfo{Version:"v3.6.2", GitCommit:"ee407bdf364942bcb8e8c665f82e15aa28009b71", GitTreeState:"clean", GoVersion:"go1.16.5"}
```
